In [ ]:

!pip install boto3 sagemaker


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.2/139.2 kB 10.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 42.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 kB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.5/12.5 MB 91.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.7/82.7 kB 8.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.8/147.8 kB 13.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.1/82.1 kB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 11.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 13.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.8/56.8 kB 5.7 MB/s eta 0:00:00
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib_metadata 8.2.0
    Uninstalling importlib_metadata-8.2.0:
      Successfully uninstalled importlib_metadata-8.2.0
  Attemp

In [ ]:
!pip install xgboost

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.9/190.9 MB 6.2 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch 2.3.1+cu121 requires nvidia-cublas-cu12==12.1.3.1; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-cuda-cupti-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-cuda-nvrtc-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-cuda-runtime-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-cudnn-cu12==8.9.2.26; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requ

In [ ]:
!pip install xgboost scikit-learn

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [ ]:
import pandas as pd

# Função para classificar o preço
def classify_price(price):
    if price <= 85:
        return 1
    elif 85 < price < 115:
        return 2
    else:
        return 3

# Carregar o dataset
base_hotel = pd.read_csv('/content/Hotel Reservations.csv')

# Criar a coluna de label
base_hotel['label_avg_price_per_room'] = base_hotel['avg_price_per_room'].apply(classify_price)

# Remover a coluna avg_price_per_room
base_hotel = base_hotel.drop(columns=['avg_price_per_room'])

# Exibir as primeiras linhas para inspeção
print(base_hotel.head())

  Booking_ID  no_of_adults  no_of_children  no_of_weekend_nights  \
0   INN00001             2               0                     1   
1   INN00002             2               0                     2   
2   INN00003             1               0                     2   
3   INN00004             2               0                     0   
4   INN00005             2               0                     1   

   no_of_week_nights type_of_meal_plan  required_car_parking_space  \
0                  2       Meal Plan 1                           0   
1                  3      Not Selected                           0   
2                  1       Meal Plan 1                           0   
3                  2       Meal Plan 1                           0   
4                  1      Not Selected                           0   

  room_type_reserved  lead_time  arrival_year  arrival_month  arrival_date  \
0        Room_Type 1        224          2017             10             2   
1        Room_

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Colunas úteis para análise, incluindo a nova coluna 'label_avg_price_per_room'
features = ['lead_time', 'no_of_special_requests', 'no_of_adults',
            'no_of_children', 'type_of_meal_plan', 'arrival_month',
            'no_of_week_nights', 'room_type_reserved', 'label_avg_price_per_room']

# Seleciona as colunas especificadas no DataFrame base_hotel
X = base_hotel[features].copy()

# Codificação das variáveis categóricas
label_encoders = {}
for column in X.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    X[column] = le.fit_transform(X[column])
    label_encoders[column] = le

# Converte o DataFrame X para um array NumPy
X = X.values

# Exibe o array X
print(X)

[[224   0   2 ...   2   0   1]
 [  5   1   2 ...   3   0   2]
 [  1   0   1 ...   1   0   1]
 ...
 [148   2   2 ...   6   0   2]
 [ 63   0   2 ...   3   0   2]
 [207   0   2 ...   2   0   3]]


In [ ]:
base_hotel.isnull().sum()

Booking_ID                              0
no_of_adults                            0
no_of_children                          0
no_of_weekend_nights                    0
no_of_week_nights                       0
type_of_meal_plan                       0
required_car_parking_space              0
room_type_reserved                      0
lead_time                               0
arrival_year                            0
arrival_month                           0
arrival_date                            0
market_segment_type                     0
repeated_guest                          0
no_of_previous_cancellations            0
no_of_previous_bookings_not_canceled    0
no_of_special_requests                  0
booking_status                          0
label_avg_price_per_room                0
dtype: int64

In [ ]:
# Seleciona apenas as colunas numéricas
numeric_df = base_hotel.select_dtypes(include=[float, int])
numeric_df.corr()

no_of_adults  no_of_children  \
no_of_adults                              1.000000       -0.019787   
no_of_children                           -0.019787        1.000000   
no_of_weekend_nights                      0.103316        0.029478   
no_of_week_nights                         0.105622        0.024398   
required_car_parking_space                0.011429        0.034244   
lead_time                                 0.097287       -0.047091   
arrival_year                              0.076719        0.045983   
arrival_month                             0.021841       -0.003076   
arrival_date                              0.026338        0.025482   
repeated_guest                           -0.192277       -0.036348   
no_of_previous_cancellations             -0.047426       -0.016390   
no_of_previous_bookings_not_canceled     -0.119166       -0.021189   
no_of_special_requests                    0.189401        0.124486   
label_avg_price_per_room                  0.260361        0.195747   

                                      no_of_weekend_nights  no_of_week_nights  \
no_of_adults                                      0.103316           0.105622   
no_of_children                                    0.029478           0.024398   
no_of_weekend_nights                              1.000000           0.179577   
no_of_week_nights                                 0.179577           1.000000   
required_car_parking_space                       -0.031111          -0.048784   
lead_time                                         0.046595           0.149650   
arrival_year                                      0.055357           0.032672   
arrival_month                                    -0.009894           0.037376   
arrival_date                                      0.027304          -0.009305   
repeated_guest                                   -0.067107          -0.099764   
no_of_previous_cancellations                     -0.020690          -0.030080   
no_of_previous_bookings_not_canceled             -0.026312          -0.049344   
no_of_special_requests                            0.060593           0.045994   
label_avg_price_per_room                         -0.032719          -0.005931   

                                      required_car_parking_space  lead_time  \
no_of_adults                                            0.011429   0.097287   
no_of_children                                          0.034244  -0.047091   
no_of_weekend_nights                                   -0.031111   0.046595   
no_of_week_nights                                      -0.048784   0.149650   
required_car_parking_space                              1.000000  -0.066445   
lead_time                                              -0.066445   1.000000   
arrival_year                                            0.015684   0.143439   
arrival_month                                          -0.015505   0.136814   
arrival_date                                           -0.000037   0.006479   
repeated_guest                                          0.110909  -0.135984   
no_of_previous_cancellations                            0.027106  -0.045723   
no_of_previous_bookings_not_canceled                    0.063810  -0.078137   
no_of_special_requests                                  0.087922  -0.101645   
label_avg_price_per_room                                0.050132  -0.020239   

                                      arrival_year  arrival_month  \
no_of_adults                              0.076719       0.021841   
no_of_children                            0.045983      -0.003076   
no_of_weekend_nights                      0.055357      -0.009894   
no_of_week_nights                         0.032672       0.037376   
required_car_parking_space                0.015684      -0.015505   
lead_time                                 0.143439       0.136814   
arrival_year                              1.000000      -0.339689   
arrival_month                    

In [ ]:
X.shape

(36275, 9)

In [ ]:
# Seleciona as colunas especificadas no DataFrame base_hotel
X = base_hotel[features].copy()  # Usar .copy() para evitar o SettingWithCopyWarning

# Exibe o DataFrame X
print(X)


       lead_time  no_of_special_requests  no_of_adults  no_of_children  \
0            224                       0             2               0   
1              5                       1             2               0   
2              1                       0             1               0   
3            211                       0             2               0   
4             48                       0             2               0   
...          ...                     ...           ...             ...   
36270         85                       1             3               0   
36271        228                       2             2               0   
36272        148                       2             2               0   
36273         63                       0             2               0   
36274        207                       0             2               0   

      type_of_meal_plan  arrival_month  no_of_week_nights room_type_reserved  \
0           Meal Plan 1        

In [ ]:
# Atribui a variável Y com os valores da coluna 'label_avg_price_per_room'
Y = numeric_df['label_avg_price_per_room'].values

# Exibe o array Y
print(Y)

[1 2 1 ... 2 2 3]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

# Função para classificar o preço
def classify_price(price):
    if price <= 85:
        return 1
    elif 85 < price < 115:
        return 2
    else:
        return 3

# Carregar o dataset
base_hotel = pd.read_csv('/content/Hotel Reservations.csv')

# Criar a coluna de label
base_hotel['label_avg_price_per_room'] = base_hotel['avg_price_per_room'].apply(classify_price)

# Remover a coluna avg_price_per_room
base_hotel = base_hotel.drop(columns=['avg_price_per_room'])

# Colunas úteis para análise, incluindo a nova coluna 'label_avg_price_per_room'
features = ['lead_time', 'no_of_special_requests', 'no_of_adults',
            'no_of_children', 'type_of_meal_plan', 'arrival_month',
            'no_of_week_nights', 'room_type_reserved', 'label_avg_price_per_room']

# Seleciona as colunas especificadas no DataFrame base_hotel
X = base_hotel[features].copy()  # Usar .copy() para evitar o SettingWithCopyWarning

# Atribui a variável Y com os valores da coluna 'label_avg_price_per_room'
Y = X.pop('label_avg_price_per_room')

# Codificação das variáveis categóricas
label_encoders = {}
for column in X.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    X[column] = le.fit_transform(X[column])
    label_encoders[column] = le

# Converte X e Y para float32
X = X.astype('float32')
Y = Y.astype('float32')

# Dividir o conjunto de dados em treinamento e teste
X_treinamento, X_teste, Y_treinamento, Y_teste = train_test_split(X, Y, test_size=0.3, random_state=0)

# Treinar o modelo
model = LogisticRegression(max_iter=1000)
model.fit(X_treinamento, Y_treinamento)

# Fazer previsões
Y_pred = model.predict(X_teste)

# Avaliar o modelo
print("Accuracy Score:", accuracy_score(Y_teste, Y_pred))
print("Classification Report:\n", classification_report(Y_teste, Y_pred))

Accuracy Score: 0.5277956445832951
Classification Report:
               precision    recall  f1-score   support

         1.0       0.52      0.39      0.44      3258
         2.0       0.46      0.64      0.53      4006
         3.0       0.68      0.53      0.59      3619

    accuracy                           0.53     10883
   macro avg       0.55      0.52      0.52     10883
weighted avg       0.55      0.53      0.53     10883

